services:
  course-service-db:
    image: postgres:16-alpine
    container_name: course-service-db
    environment:
      POSTGRES_DB: course_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - course_service_db_data:/var/lib/postgresql/data
      - ./services/course-service/src/main/resources/db.migration/V1__init_course_schema.sql:/docker-entrypoint-initdb.d/01-init-course-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d course_service"]
      interval: 5s
      timeout: 5s
      retries: 10

  course-service:
    build:
      context: .
      dockerfile: services/course-service/Dockerfile
    container_name: course-service
    depends_on:
      course-service-db:
        condition: service_healthy
    environment:
      COURSE_SERVICE_DB_URL: jdbc:postgresql://course-service-db:5432/course_service
      COURSE_SERVICE_DB_USERNAME: postgres
      COURSE_SERVICE_DB_PASSWORD: postgres
    ports:
      - "8080:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8089:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: coursehub-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

volumes:
  course_service_db_data:


