spring:
  application:
    name: course-service
  datasource:
    url: ${COURSE_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/course_service}
    username: ${COURSE_SERVICE_DB_USERNAME:postgres}
    password: ${COURSE_SERVICE_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


mybatis:
  mapper-locations: classpath*:mybatis/**/*.xml
  type-aliases-package: course.courseservice.infrastructure.persistence.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
